# -*- coding: utf-8 -*-
"""Day2_HW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oKd1DQjOZYUKTJvasnGUiJAf0cDJf9d1
"""

mylist=[0,1,2,3,4,5,6,7,8,9,10]
for i in range(int((len(mylist)/2))):
    temp=mylist[-1-i]
    mylist[-1-i]=mylist[i]
    mylist[i]=temp
print(mylist)

n=int(input("0-10 arasında integer girin\n"))

if n<10 and n>=0:
  for i in range((n+1)):
    if i%2==0:
      print(i)
    else:
      continue
else:
  n=int(input("girdiğiniz deger 0 ile 10 arasında değildir.Yeni değer giriniz"))
  for i in range((n+1)):
    if i%2==0:
      print(i)
    else:
      continue